---
title: "FibroblastAnalysisDEgenes_wtonly_withoutGlial"
author: "A.DeMartin"
date: "2025-05-20"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
```

## load object merged allFb d4
```{r load object merged allFb d4}
##load object merged allFb naive and d4
fileNam <- "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/data/merged_allFb_naiveANDd4_seurat.rds"
seuratFb <- readRDS(fileNam)
table(seuratFb$dataset)
```

## subset wt
```{r subset wt}
table(seuratFb$cond2)
seuratwt <- subset(seuratFb, cond2 == "WT")
table(seuratwt$cond2)

table(seuratwt$clustername)
seuratnoglial <- subset(seuratwt, clustername == "Glial", invert = TRUE)
table(seuratnoglial$clustername)

seuratFb <- seuratnoglial
```

## set color vectors 
```{r colors}
## set vector for cond2
colcond2 <- c("#202547","#BE3144")
names(colcond2) <- c("WT", "cko")

## set vector for cond2
colcond3 <- c("#B45B5C","#628395","#BF782D")
names(colcond3) <- c("infectedD4", "naive", "granulomaD4")

#colPal <- c("#355C7D", "#8E9B97","#779d8d","#0F1F38","#E84A5F","#FF847C","#F8B195", "#727077", "#C06C84","#2A363B", "#6C5B7B")
#names(colPal) <- c("0" ,"1", "2", "3", "4", "5", "6", "7", "8", "9", "10")

colPal <- c("#355C7D", "#8E9B97","#99B898","#E84A5F","#0F1F38","#FF847C","#F8B195","#6C5B7B", "#C06C84", "#727077")
names(colPal) <- c("0" ,"1", "2", "3","4", "5", "6", "7", "8", "9")

colclustername <- c("#355C7D", "#8E9B97","#99B898","#E84A5F","#0F1F38","#F8B195","#727077","#FF847C","#C06C84","#904D39")
names(colclustername) <- c("PdgfraloFb1" ,"PdgfraloFb2", "Trophocytes","PdgfraloFb3", "Telocytes","Myocytes", "Pdgfrahi", "PdgfraloFb4", "Thy1Fb", "Glial")
```

## calculate DE genes according to cond3
```{r DE genes cond3, include=TRUE, eval=FALSE}
## calculate DE genes
Idents(seuratFb) <- seuratFb$cond3
levels(seuratFb)

DEGenesFbcond3 <- FindAllMarkers(seuratFb, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01) 

write.table(DEGenesFbcond3, 
            file= "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/data/DEGenesFbcond3_wtonly_noglial.txt",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)
```

## GSEA Fb gran
```{r GSEA Fb gran, fig.height=12, fig.width=12}
## load DEGenesFbcond3
DEGenesFbcond3 <- read.delim("/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/data/DEGenesFbcond3_wtonly_noglial.txt", header = TRUE, sep = "\t")

## GSEA on genes upregulated in granulomaFb
##adjust table
DEGenesGran <- dplyr::filter(DEGenesFbcond3, cluster == "granulomaD4")
DEGenesGran <- DEGenesGran %>%
  mutate(Gene=gsub("^.*\\.", "", gene))  %>%
  mutate(EnsID=gsub("\\..*","", gene))

##GSEA Gran
egoGran <- enrichGO(gene = unique(DEGenesGran$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoGran <- setReadable(egoGran, OrgDb = org.Mm.eg.db)
dotplot(egoGran, showCategory=30)
```

## barplot GSEA gran
```{r barplot GSEA Fb gran, fig.height=5, fig.width=12}
#select pahtways and filter file
selGran <- c("leukocyte migration","regulation of innate immune response", "mitochondrial translation", "response to interferon-beta")
egoGran_fil <- egoGran%>% filter(egoGran@result$Description %in% selGran)

egoGran_fil_2 <- pairwise_termsim(egoGran_fil)
#make ggbarplot
p <- ggbarplot(egoGran_fil_2@result, x = "Description", y = "Count", fill = "#BF782D", color= "#BF782D", sort.val = "asc", orientation = "horizontal")
p
```

## convert to sce 
```{r convert to sce}
##convert seurat object to sce object
sce <- as.SingleCellExperiment(seuratFb)
genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582", "#b2183c", "#85122d"))

##subset naive and convert to sce
seuratFbnaive <- subset(seuratFb, cond3 == "naive")
DimPlot(seuratFbnaive, reduction= "umap") + theme(legend.position = "none")
sceFbnaive <- as.SingleCellExperiment(seuratFbnaive)

##subset SI and convert to sce
seuratFbinf <- subset(seuratFb, cond3 == "infectedD4")
DimPlot(seuratFbinf, reduction= "umap") + theme(legend.position = "none")
sceFbinf <- as.SingleCellExperiment(seuratFbinf)

##subset Gran and convert to sce
seuratFbgran <- subset(seuratFb, cond3 == "granulomaD4")
DimPlot(seuratFbgran, reduction= "umap") + theme(legend.position = "none")
sceFbgran <- as.SingleCellExperiment(seuratFbgran)
```

## plot GSEA signatures onto umaps gran
```{r plot GSEA leukocyte migration}
## GSEA on genes upregulated in granuloma
ego1 <- dplyr::filter(egoGran@result,egoGran@result$Description=="leukocyte migration")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

signGenes <- genes %>% dplyr::filter(gene %in% df$gene)
##make a count matrix of signature genes
sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.6))
sceSub$sign2[which(sceSub$sign > 0.6)] <- 0.6
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.6))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 0.6)] <- 0.6
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.6))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 0.6)] <- 0.6
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.6))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 0.6)] <- 0.6
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

```{r plot GSEA positive regualtion of innate immune response}
## GSEA on genes upregulated in granuloma
ego1 <- dplyr::filter(egoGran@result,egoGran@result$Description=="regulation of innate immune response")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceSub$sign2[which(sceSub$sign > 0.7)] <- 0.7
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 0.7)] <- 0.7
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 0.7)] <- 0.7
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 0.7)] <- 0.7
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

## GSEA Fb SI
```{r GSEA Fb SI, fig.height=12, fig.width=12}
## GSEA on genes upregulated in SI
##adjust table
DEGenesinf <- dplyr::filter(DEGenesFbcond3, cluster == "infectedD4")
DEGenesinf <- DEGenesinf %>%
  mutate(Gene=gsub("^.*\\.", "", gene))  %>%
  mutate(EnsID=gsub("\\..*","", gene))

##GSEA inf
egoinf <- enrichGO(gene = unique(DEGenesinf$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoinf <- setReadable(egoinf, OrgDb = org.Mm.eg.db)
dotplot(egoinf, showCategory=30)
```

## barplot GSEA SI
```{r barplot GSEA Fb SI, fig.height=5, fig.width=12}
#select pahtways and filter file
selSI <- c("extracellular matrix organization","regulation of cellular response to growth factor stimulus", "regulation of Wnt signaling pathway", "response to virus")
egoSI_fil <- egoinf%>% filter(egoinf@result$Description %in% selSI)

egoSI_fil_2 <- pairwise_termsim(egoSI_fil)
#make ggbarplot
p <- ggbarplot(egoSI_fil_2@result, x = "Description", y = "Count", fill = "#B45B5C", color= "#B45B5C", sort.val = "asc", orientation = "horizontal")
p
```

## plot GSEA signatures onto umaps inf
```{r plot GSEA extracellular matrix organization}
## GSEA on genes upregulated in inf
ego1 <- dplyr::filter(egoinf@result,egoinf@result$Description=="extracellular matrix organization")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.4))
sceSub$sign2[which(sceSub$sign > 1.4)] <- 1.4
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.4))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 1.4)] <- 1.4
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.4))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 1.4)] <- 1.4
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.4))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 1.4)] <- 1.4
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```


```{r plot GSEA regulation of cellular response to growth factor stimulus}
## GSEA on genes upregulated in inf
ego1 <- dplyr::filter(egoinf@result,egoinf@result$Description=="regulation of cellular response to growth factor stimulus")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.2))
sceSub$sign2[which(sceSub$sign > 1.2)] <- 1.2
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.2))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 1.2)] <- 1.2
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.2))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 1.2)] <- 1.2
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 1.2))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 1.2)] <- 1.2
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

## GSEA Fb naive
```{r GSEA Fb naive, fig.height=12, fig.width=12}
## GSEA on genes upregulated in naive
##adjust table
DEGenesnaive <- dplyr::filter(DEGenesFbcond3, cluster == "naive")
DEGenesnaive <- DEGenesnaive %>%
  mutate(Gene=gsub("^.*\\.", "", gene))  %>%
  mutate(EnsID=gsub("\\..*","", gene))

##GSEA inf
egonaive <- enrichGO(gene = unique(DEGenesnaive$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egonaive <- setReadable(egonaive, OrgDb = org.Mm.eg.db)
dotplot(egonaive, showCategory=30)
```

## barplot GSEA naive
```{r barplot GSEA Fb naive, fig.height=5, fig.width=12}
#select pahtways and filter file
selnaive <- c("negative regulation of phosphate metabolic process", "response to steroid hormone", "G1/S transition of mitotic cell cycle", "regulation of developmental growth")
egonaive_fil <- egonaive%>% filter(egonaive@result$Description %in% selnaive)

egonaive_fil_2 <- pairwise_termsim(egonaive_fil)
#make ggbarplot
p <- ggbarplot(egonaive_fil_2@result, x = "Description", y = "Count", fill = "#628395", color= "#628395", sort.val = "asc", orientation = "horizontal")
p
```

## plot GSEA signatures onto umaps naive
```{r plot GSEA negative regulation of phosphate metabolic process}
## GSEA on genes upregulated in naive
ego1 <- dplyr::filter(egonaive@result,egonaive@result$Description =="negative regulation of phosphate metabolic process")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceSub$sign2[which(sceSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

```{r plot GSEA response to steroid hormone}
## GSEA on genes upregulated in naive
ego1 <- dplyr::filter(egonaive@result,egonaive@result$Description =="response to steroid hormone")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceSub$sign2[which(sceSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

```{r plot GSEA G1/S transition of mitotic cell cycle}
## GSEA on genes upregulated in naive
ego1 <- dplyr::filter(egonaive@result,egonaive@result$Description =="G1/S transition of mitotic cell cycle")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceSub$sign2[which(sceSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceSub$sign)
plotUMAP(sceSub, colour_by = "sign2") + sc +
  theme(legend.position = "none", point_size = 1)
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc

##make a count matrix of signature genes naive
sceFbnaiveSub <- sceFbnaive[which(rownames(sceFbnaive) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbnaiveSub@assays@data$logcounts)))/nrow(signGenes)
sceFbnaiveSub$sign <- cntMat
sceFbnaiveSub$sign2 <- sceFbnaiveSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbnaiveSub$sign2[which(sceFbnaiveSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbnaiveSub$sign)
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbnaiveSub, colour_by = "sign2", point_size = 1) + sc


##make a count matrix of signature genes inf
sceFbinfSub <- sceFbinf[which(rownames(sceFbinf) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbinfSub@assays@data$logcounts)))/nrow(signGenes)
sceFbinfSub$sign <- cntMat
sceFbinfSub$sign2 <- sceFbinfSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbinfSub$sign2[which(sceFbinfSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbinfSub$sign)
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbinfSub, colour_by = "sign2", point_size = 1) + sc


##make a count matrix of signature genes gran
sceFbgranSub <- sceFbgran[which(rownames(sceFbgran) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceFbgranSub@assays@data$logcounts)))/nrow(signGenes)
sceFbgranSub$sign <- cntMat
sceFbgranSub$sign2 <- sceFbgranSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.9))
sceFbgranSub$sign2[which(sceFbgranSub$sign > 0.9)] <- 0.9
##check max and min values
max(sceFbgranSub$sign)
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceFbgranSub, colour_by = "sign2", point_size = 1) + sc
```

## plot violin Il33
```{r violin}
Idents(seuratFb) <- seuratFb$cond3
VlnPlot(object = seuratFb, features = "ENSMUSG00000024810.Il33", pt.size = 0, cols = colcond3)
```

## session info
```{r date and session info}
date()
sessionInfo()
```
