---
title: "FibroblastAnalysisDEgenes"
author: "A.DeMartin"
date: "2024-07-17"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Mm.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
```

## load object merged allFb d4
```{r load object merged allFb d4}
##load object merged allFb naive and d4
fileNam <- "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/data/merged_allFb_naiveANDd4_seurat.rds"
seuratFb <- readRDS(fileNam)
table(seuratFb$dataset)
```

## set color vectors 
```{r colors}
## set vector for cond2
colcond2 <- c("#202547","#BE3144")
names(colcond2) <- c("WT", "cko")

## set vector for cond2
colcond3 <- c("#202547","#628395","#BE3144")
names(colcond3) <- c("infectedD4", "naive", "granulomaD4")

#colPal <- c("#355C7D", "#8E9B97","#779d8d","#0F1F38","#E84A5F","#FF847C","#F8B195", "#727077", "#C06C84","#2A363B", "#6C5B7B")
#names(colPal) <- c("0" ,"1", "2", "3", "4", "5", "6", "7", "8", "9", "10")

colPal <- c("#355C7D", "#8E9B97","#99B898","#E84A5F","#0F1F38","#FF847C","#F8B195","#6C5B7B", "#C06C84", "#727077")
names(colPal) <- c("0" ,"1", "2", "3","4", "5", "6", "7", "8", "9")

colclustername <- c("#355C7D", "#8E9B97","#99B898","#E84A5F","#0F1F38","#FF847C","#F8B195","#6C5B7B", "#C06C84", "#727077")
names(colclustername) <- c("PdgfraloFb1" ,"PdgfraloFb2", "Trophocytes","PdgfraloFb3", "Telocytes","Myocytes", "Pdgfrahi", "PdgfraloFb4", "Thy1Fb", "Glial")
```

## calculate cluster marker genes
```{r marker gens, include=TRUE, eval=FALSE}
## calculate marker genes
Idents(seuratFb) <- seuratFb$clustername
levels(seuratFb)

markerGenes <- FindAllMarkers(seuratFb, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01) 

write.table(markerGenes, 
            file= "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/analysis/FbmarkerGenesclustername.txt",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)
```

## calculate DE genes according to cond3
```{r DE genes cond3, include=TRUE, eval=FALSE}
## calculate DE genes
Idents(seuratFb) <- seuratFb$cond3
levels(seuratFb)

DEGenesFbcond3 <- FindAllMarkers(seuratFb, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01) 

write.table(DEGenesFbcond3, 
            file= "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/analysis/DEGenesFbcond3.txt",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)

DEGenesFbcond3_0.1 <- DEGenesFbcond3 %>% dplyr::filter(avg_log2FC > 0.1) %>% dplyr::filter(p_val_adj < 1e-50) %>% dplyr::filter(cluster == "granulomaD4")
```

## GSEA Fb
```{r GSEA Fb, fig.height=12, fig.width=12}
## load DEGenesFbcond3
DEGenesFbcond3 <- read.delim("FbDEGenescond3.txt", header = TRUE, sep = "\t")

## GSEA on genes upregulated in granulomaFb
##adjust table
DEGenesGran <- dplyr::filter(DEGenesFbcond3, cluster == "granulomaD4")
DEGenesGran <- DEGenesGran %>%
  mutate(Gene=gsub("^.*\\.", "", gene))  %>%
  mutate(EnsID=gsub("\\..*","", gene))

##GSEA Gran
egoGran <- enrichGO(gene = unique(DEGenesGran$EnsID),
                          OrgDb = org.Mm.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoGran <- setReadable(egoGran, OrgDb = org.Mm.eg.db)
dotplot(egoGran, showCategory=30)
```

## convert to sce 
```{r convert to sce}
##convert seurat object to sce object
sce <- as.SingleCellExperiment(seuratFb)
genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582", "#b2183c", "#85122d"))
```

## plot GSEA signatures onto umaps
```{r plot GSEA genes leukocyte migration}
## GSEA on genes upregulated in granuloma
ego1 <- dplyr::filter(egoGran@result,egoGran@result$Description=="leukocyte migration")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceSub$sign2[which(sceSub$sign > 0.7)] <- 0.7
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc
##check max and min values
max(sceSub$sign)
```

## plot GSEA signatures onto umaps
```{r plot GSEA genes positive regualtion of innate immune response}
## GSEA on genes upregulated in granuloma
ego1 <- dplyr::filter(egoGran@result,egoGran@result$Description=="positive regulation of innate immune response")
g1 <- ego1$geneID
Str <-(g1)
StrSub <- strsplit(Str, "/")
df <- as.data.frame(StrSub)
colnames(df) <- c("gene")

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% df$gene)

sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)
sceSub$sign <- cntMat
sceSub$sign2 <- sceSub$sign
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 0.7))
sceSub$sign2[which(sceSub$sign > 0.7)] <- 0.7
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc +
  theme(legend.position = "none")
plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc
##check max and min values
max(sceSub$sign)
```

## calculate DE genes according to cond2
```{r DE genes cond2, include=TRUE, eval=FALSE}
## calculate DE genes
Idents(seuratFb) <- seuratFb$cond2
levels(seuratFb)

DEGenesFbcond2 <- FindAllMarkers(seuratFb, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01) 

write.table(DEGenesFbcond2, 
            file= "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/analysis/DEGenesFbcond2.txt",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)

DEGenesFbcond2_0.1 <- DEGenesFbcond2 %>% dplyr::filter(avg_log2FC > 0.1) %>% dplyr::filter(p_val_adj < 1e-50) %>% dplyr::filter(cluster == "WT") 

## subset infected only
seuratD4 <- subset(seuratFb, cond3 %in% c("infectedD4", "granulomaD4"))
table(seuratD4$cond3)
## calculate DE genes cond2
Idents(seuratD4) <- seuratD4$cond2
levels(seuratD4)

DEGenesD4cond2 <- FindAllMarkers(seuratD4, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01) 

write.table(DEGenesD4cond2, 
            file= "/Users/immbio/Desktop/Project/Angelina/Cxcl13Hpb/analysis/DEGenesD4cond2.txt",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)
```

## Venn diagram
```{r Venn}
## load DEGenesFbcond2
DEGenesFbcond2 <- read.delim("GranDEGenescond2.txt", header = TRUE, sep = "\t")

## GSEA on genes upregulated in granulomaFb
##adjust table
DEGenesGran <- dplyr::filter(DEGenesFbcond2, cluster == "granulomaD4")
DEGenesGran <- DEGenesGran %>%
  mutate(Gene=gsub("^.*\\.", "", gene))  %>%
  mutate(EnsID=gsub("\\..*","", gene))

##make Venn Diagram
x <- list(UpInWT=DEGenesFbcond2_0.1$gene,
          UpInGran=DEGenesFbcond3_0.1$gene)
library(VennDiagram)
venn.diagram(x, filename = "venn-4-diagram.png")
# Helper function to display Venn diagram
display_venn <- function(z, ...) {
  grid.newpage()
  venn_object <- venn.diagram (z, filename = NULL, ...)
  grid.draw (venn_object)
}
display_venn(x)
# change fill color and circles
display_venn(x, fill = c("#2166AC", "#B2182B") lwd = 5, lty = 'blank')
## extract genes in intersections
library(gplots)
vTab <- venn(x)
# extract genes in intersections
vTab
```

## session info
```{r date and session info}
date()
sessionInfo()
```
