---
title: "Fibroblast - Macrophage crosstalk in granuloma formation"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
## Granuloma Cells
### GranulomaAllcells
Granuloma Analysis
[link](GranulomaAnalysis.html)

### InteractionGranuloma
Cellchat
[link](CellChatGranuloma.html)

### GranulomaMacrophages 
Gran Macrophage Analysis
[link](GranulomaMacrophages.html)

## Fibroblasts
### Fibroblast Analysis
Fibroblast Analysis all
[link](FibroblastAnalysis.html)

### Fibroblast Analysis wt only
Fibroblast Analysis wt only
[link](FibroblastAnalysis_wtonly.html)

### Fibroblast Analysis DE genes
Fibroblast Analysis DE genes
[link](FibroblastAnalysisDEgenes.html)

### Fibroblast Analysis DE genes without Glia
Fibroblast Analysis DE genes without Glia
[link](FibroblastAnalysisDEgenes_withoutGlial.html)

### Fibroblast Analysis DE genes wt only
Fibroblast Analysis DE genes wt only
[link](FibroblastAnalysisDEgenes_wtonly.html)

### Fibroblast Analysis DE genes wt only without Glia
Fibroblast Analysis DE genes wt only without Glia
[link](FibroblastAnalysisDEgenes_wtonly_withoutGlial.html)

### FRC signatures
FRC signatures
[link](FRCsignatures.html)

### Gran Fibroblasts
Gran Fibroblasts
[link](GranFb.html)

### Gran Fibroblasts without Glia
Gran Fibroblasts without Glia
[link](GranFb_withoutGlial.html)

### Fibroblast analysis including D8 
Fibroblast analysis including D8 data
[link](FibroblastAnalysisincl.D8.html)
